#! /bin/bash

SHELL_DIR=$(dirname $(readlink -f $0))
TEST_DIR=$SHELL_DIR/linux_test
# everything generated by the test (binaries, odbc config, log) is kept here
TEST_BUILD_DIR=$TEST_DIR/build
DRIVER_INSTALL_DIR=$HOME/cubrid-odbc/lib
UNIXODBC_DIR=$SHELL_DIR/build/external
ODBCINST_INI_FILE=$TEST_BUILD_DIR/odbcinst.ini
ODBC_INI_FILE=$TEST_BUILD_DIR/odbc.ini
TEST_LOG_FILE=$TEST_BUILD_DIR/odbc_test.log

TEST_DB_SERVER=
TEST_DB_PORT=33000
TEST_DB_NAME=demodb
TEST_DB_USER=dba
TEST_DB_PASSWORD=
TEST_DB_CHARSET=ko_KR.utf8
# link2 uses the ANSI driver, link2u uses the Unicode driver
TEST_DSN=link2u
TEST_GROUP=
ONLY_TEST=0
VERBOSE=0

function show_usage ()
{
  echo "Usage: $0 [OPTIONS] [TESTCASE ...]"
  echo " OPTIONS"
  echo "  -t      Only test, skip the driver build (default: false)"
  echo "  -i      Driver install directory (default: $HOME/cubrid-odbc/lib)"
  echo "  -s      Test database server (required)"
  echo "  -p      Test database broker port (default: 33000)"
  echo "  -b      Test database name (default: demodb)"
  echo "  -u      Test database user (default: dba)"
  echo "  -w      Test database password (default: \"\")"
  echo "  -n      DSN to test, link2(ANSI) or link2u(Unicode) (default: link2u)"
  echo "  -g      Run the testcases of linux_test/testcases/GROUP only (default: all groups)"
  echo "  -v      Print the full test log, not only the failed testcases (default: false)"
  echo "  -? | -h Show this help message and exit"
  echo ""
  echo " TESTCASE"
  echo "  name of the testcase to run, e.g. sql_tablesw (default: all testcases)"
  echo ""
  echo " EXAMPLES"
  echo "  $0 -s 127.0.0.1                        # build the driver and run every testcase"
  echo "  $0 -t -s 127.0.0.1 -g default-spec     # run the testcases of testcases/default-spec"
  echo "  $0 -t -s 127.0.0.1 sql_tablesw         # run sql_tablesw only"
  echo ""
}

function get_options ()
{
  while getopts ":ti:s:p:b:u:w:n:g:vh" opt; do
    case $opt in
      t ) ONLY_TEST=1;;
      i ) DRIVER_INSTALL_DIR="$OPTARG" ;;
      s ) TEST_DB_SERVER="$OPTARG" ;;
      p ) TEST_DB_PORT="$OPTARG" ;;
      b ) TEST_DB_NAME="$OPTARG" ;;
      u ) TEST_DB_USER="$OPTARG" ;;
      w ) TEST_DB_PASSWORD="$OPTARG" ;;
      n ) TEST_DSN="$OPTARG" ;;
      g ) TEST_GROUP="$OPTARG" ;;
      v ) VERBOSE=1 ;;
      h|\?|* ) show_usage; exit 1;;
    esac
  done
}

get_options "$@"
shift $(($OPTIND - 1))
TEST_CASES="$@"

if [ -z "$TEST_DB_SERVER" ]; then
  echo "Error: -s is required"
  show_usage
  exit 1
fi

if [ $ONLY_TEST -eq 0 ]; then
  if [ ! -d "$DRIVER_INSTALL_DIR" ]; then
    mkdir -p $DRIVER_INSTALL_DIR
  fi
  $SHELL_DIR/build.sh -i $DRIVER_INSTALL_DIR || exit 1
fi

if [ ! -f "$DRIVER_INSTALL_DIR/libcubrid-odbcw.so" ]; then
  echo "Error: $DRIVER_INSTALL_DIR/libcubrid-odbcw.so is not found"
  echo "Build the driver first: $SHELL_DIR/build.sh -i $DRIVER_INSTALL_DIR"
  exit 1
fi

echo "========== build the testcases of $TEST_DIR =========="
cmake -S $TEST_DIR -B $TEST_BUILD_DIR -DUNIXODBC_DIR=$UNIXODBC_DIR || exit 1
cmake --build $TEST_BUILD_DIR -- -j4 || exit 1

# unixODBC reads odbcinst.ini and odbc.ini from $ODBCSYSINI, so the test does
# not need a driver registered in /usr/local/etc or in $HOME
echo "========== write $ODBCINST_INI_FILE =========="
cat > $ODBCINST_INI_FILE <<END_OF_ODBCINST_INI
[CUBRID ODBC Driver]
Description = CUBRID Linux ODBC Driver
Driver = $DRIVER_INSTALL_DIR/libcubrid-odbc.so
FileUsage = 1

[CUBRID ODBC Driver Unicode]
Description = CUBRID Linux ODBC Unicode Driver
Driver = $DRIVER_INSTALL_DIR/libcubrid-odbcw.so
IANAAppCodePage = 1

[CUBRID Driver Unicode]
Description = CUBRID Linux ODBC Unicode Driver
Driver = $DRIVER_INSTALL_DIR/libcubrid-odbcw.so
IANAAppCodePage = 1
END_OF_ODBCINST_INI
cat $ODBCINST_INI_FILE

echo "========== write $ODBC_INI_FILE =========="
cat > $ODBC_INI_FILE <<END_OF_ODBC_INI
[link2]
Driver = CUBRID ODBC Driver
Description = CUBRID ODBC
DB_NAME = $TEST_DB_NAME
UID = $TEST_DB_USER
PWD = $TEST_DB_PASSWORD
SERVER = $TEST_DB_SERVER
PORT = $TEST_DB_PORT
FETCH_SIZE = 1
AUTOCOMMIT = false
OMIT_SCHEMA = no
CHARSET = $TEST_DB_CHARSET

[link2u]
Driver = CUBRID ODBC Driver Unicode
Description = CUBRID ODBC Unicode
DB_NAME = $TEST_DB_NAME
UID = $TEST_DB_USER
PWD = $TEST_DB_PASSWORD
SERVER = $TEST_DB_SERVER
PORT = $TEST_DB_PORT
FETCH_SIZE = 1
AUTOCOMMIT = false
OMIT_SCHEMA = no
CHARSET = $TEST_DB_CHARSET
END_OF_ODBC_INI
cat $ODBC_INI_FILE

export ODBCSYSINI=$TEST_BUILD_DIR
export ODBCINI=$ODBC_INI_FILE
export LD_LIBRARY_PATH=$DRIVER_INSTALL_DIR:$UNIXODBC_DIR/lib:/usr/local/lib:$LD_LIBRARY_PATH

TEST_OPTIONS="-d $TEST_DSN -l $TEST_LOG_FILE"
if [ -n "$TEST_GROUP" ]; then
  TEST_OPTIONS="$TEST_OPTIONS -g $TEST_GROUP"
fi
if [ $VERBOSE -eq 1 ]; then
  TEST_OPTIONS="$TEST_OPTIONS -v"
fi

echo "========== run the $TEST_DSN test =========="
$TEST_BUILD_DIR/odbc_test $TEST_OPTIONS $TEST_CASES
TEST_RESULT=$?

echo "========== test completed (exit code: $TEST_RESULT) =========="

exit $TEST_RESULT
