# sample odbcinst.ini, test.sh generates the same file in linux_test/build
[CUBRID ODBC Driver]
Description	= CUBRID Linux ODBC Driver
Driver		= /home/cubrid/cubrid-odbc/lib/libcubrid-odbc.so
FileUsage	= 1

[CUBRID ODBC Driver Unicode]
Description	= CUBRID Linux ODBC Unicode Driver
Driver		= /home/cubrid/cubrid-odbc/lib/libcubrid-odbcw.so
IANAAppCodePage	= 1

[CUBRID Driver Unicode]
Description	= CUBRID Linux ODBC Unicode Driver
Driver		= /home/cubrid/cubrid-odbc/lib/libcubrid-odbcw.so
IANAAppCodePage	= 1
