#ifndef _ODBC_TEST_H
#define _ODBC_TEST_H

#include <sql.h>
#include <sqlext.h>

#define LINUXODBC_TESTLIB "libcubrid-odbc-test.so"
/* testcase list generated by cmake from testcases/<group>/sql_*.c */
#define TESTCASE_LIST "testcases.lst"
#define DEFAULT_DSN "link2u"
#define DEFAULT_LOG "odbc_test.log"
#define CASE_PREFIX "sql_"
#define MAX_TEST_CASES 512
#define PATHMAX 1024
#define NAMEMAX 256
#define DSNFILE "dsn.txt"

#define IS_LOADED(idx)       (odbc_testcases[idx].func!=NULL)

enum
{ TRUE = 1, FALSE = 0 };

typedef struct
{
  char name[NAMEMAX];
  char group[NAMEMAX];

  SQLRETURN (*func) ();
} testcase_t;

int load_linux_odbc_testcases (const char *dir);
int testcase_exists (char *casename);

#endif /* _ODBC_TEST_H */
